# Generated by Django 6.1.1 on 2026-09-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('artista', models.CharField(max_length=100)),
                ('lanzamiento', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'servicios',
                'ordering': ['titulo'],
            },
        ),
    ]
